stages:
    - build

.build-base:
    image: registry.videolan.org/vlc-debian-llvm-mingw:20190621125349
    tags:
        - docker
        - amd64
    stage: build
    script:
        - git clone https://code.videolan.org/videolan/vlc/ && cd vlc && extras/package/win32/build.sh -c -r -x -l -i n -a $ARCH 
    after_script:
        - mkdir nightlies
        - cp ./vlc/win64/vlc-4.0.0-dev-win64.7z nightlies
    artifacts:
        paths:
            - nightlies/*
        expire_in: 2 weeks

build-x86_64:
    extends: .build-base
    variables:
        ARCH: x86_64
        SHORTARCH: win64