stages:
    - build
    - build-unity-plugin

variables:
    VLC_UWP_LLVM_IMAGE: registry.videolan.org/vlc-debian-llvm-uwp:20211020111246
    VLC_WIN_LLVM_IMAGE: registry.videolan.org/vlc-debian-llvm-mingw:20211020094514
    VLC_DEBIAN_IMAGE: registry.videolan.org/vlc-debian-unstable:20210803114245

.win-common:
    tags:
        - docker
        - amd64
    stage: build
    script:
        - git clone https://code.videolan.org/videolan/vlc/ && cd vlc 
        - wget -O disable-activex.patch https://code.videolan.org/-/snippets/1304/raw
        - git apply disable-activex.patch
        - extras/package/win32/build.sh $ARGS 
    after_script:
        - mkdir nightlies
        - ls ./vlc/win64
        - cd ./vlc/$BUILD_FOLDER
        - make package-win-strip
        - ls vlc-4.0.0-dev
        - 7z a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on $ARTIFACT $OUTPUT
        - cp $ARTIFACT ../../nightlies
    artifacts:
        paths:
            - nightlies/*
        expire_in: 2 weeks
    variables:
        WINE_SDK_PATH: /usr/include/wine/wine/windows/
        OUTPUT: ./vlc-4.0.0-dev

.build-plugin-base:
    image: 
        name: $VLC_WIN_LLVM_IMAGE
    dependencies: 
        - libvlc-x86_64
    tags:
        - docker
        - amd64
    stage: build-unity-plugin
    script:
        - 7z x ./nightlies/vlc-4.0.0-dev-win64.7z -o./build
        - mkdir -p Assets/VLCUnity/Plugins/x86_64
        - cp -R ./build/vlc-4.0.0-dev/{libvlc.dll,libvlccore.dll,hrtfs,lua,plugins} Assets/VLCUnity/Plugins/x86_64
        - rm -rf Assets/VLCUnity/Plugins/x86_64/lua/http
        - cp -r ./build/vlc-4.0.0-dev/sdk/ PluginSource/
        - ./build.sh
    after_script:
        - cp Assets/VLCUnity/Plugins/x86_64/VLCUnityPlugin.dll nightlies
    artifacts:
        paths:
            - nightlies/*
        expire_in: 2 weeks

libvlc-x86_64-debug:
    extends: .win-common
    image: 
        name: $VLC_WIN_LLVM_IMAGE
    variables:
        ARGS: -c -z -d -x -a x86_64
        ARTIFACT: vlc-4.0.0-dev-win64-debug.7z
        BUILD_FOLDER: win64
        
libvlc-x86_64:
    extends: .win-common
    image: 
        name: $VLC_WIN_LLVM_IMAGE
    variables:
        ARGS: -c -z -r -x -a x86_64 -i nope
        ARTIFACT: vlc-4.0.0-dev-win64.7z
        BUILD_FOLDER: win64

libvlc-uwp64-llvm:
    extends: .win-common
    image:
        name: $VLC_UWP_LLVM_IMAGE
    variables:
        ARGS: -w -u -c -z -r -x -a x86_64 -i nope
        ARTIFACT: vlc-4.0.0-dev-win64.7z
        BUILD_FOLDER: win64-uwp

libvlc-uwp64-llvm-debug:
    extends: .win-common
    image:
        name: $VLC_UWP_LLVM_IMAGE
    variables:
        ARGS: -w -u -c -z -d -x -a x86_64
        ARTIFACT: vlc-4.0.0-dev-win64-debug.7z
        BUILD_FOLDER: win64-uwp
            
libvlcsharp-unity:
    image:
        name: $VLC_DEBIAN_IMAGE
    tags:
        - docker
        - amd64
    stage: build
    script:
        - wget https://download.visualstudio.microsoft.com/download/pr/0c795076-b679-457e-8267-f9dd20a8ca28/02446ea777b6f5a5478cd3244d8ed65b/dotnet-sdk-3.1.300-linux-x64.tar.gz
        - mkdir -p $HOME/dotnet && tar zxf dotnet-sdk-3.1.300-linux-x64.tar.gz -C $HOME/dotnet
        - export DOTNET_ROOT=$HOME/dotnet
        - export PATH=$PATH:$HOME/dotnet
        - dotnet --version
        - mkdir tmp && cd tmp && git clone https://code.videolan.org/videolan/LibVLCSharp lvs
        - cd lvs
        - git checkout -f master
        - dotnet publish src/LibVLCSharp/LibVLCSharp.csproj /p:UNITY=true -c Release
    after_script:
        - mkdir nightlies
        - cp -r tmp/lvs/src/LibVLCSharp/bin/Release/netstandard2.0/publish nightlies
    artifacts:
        paths:
            - nightlies/*
        expire_in: 2 weeks

unity-plugin-windows:
    extends: .build-plugin-base

unity-plugin-windows-trial:
    extends: .build-plugin-base
    before_script:
        - wget -O trial.patch https://code.videolan.org/snippets/1250/raw
        - git apply trial.patch
